### ISSUE TITLE
Star Schema in SQL Server -> Flat table

### ISSUE THREAD

**Issue by sheepworrier** [josesamos/starschemar#1]
Great looking package from reading the vignette.  Just wondering if you have an existing star schema database on, say, MSSQL - could you read that into one of your star schema objects somehow and then use the star_schema_as_flat_table function to generate a flat table?
I have started doing this process manually on a decent sized model with about 15 FACT and 15 Dimension tables and it’s quite a chore, so wondered if your package could speed things up?

**Comment by josesamos** [comment]
Thanks for your interest. Sorry but now the package only supports the definition of the star schema from a flat table.

I plan to generate the tables for different DBMS as a possible result. I think it would also be interesting to be able to import star schemas from DBMS (like the situation you describe), I will also take that into account for future extensions.

**Comment by josesamos** [comment]
Thinking about the problem, from Excel or Power BI (even from Access) it is possible to connect with MSSQL and generate the flat tables perhaps more easily than directly in SQL.

**Comment by sheepworrier** [comment]
Thanks for the swift reply. Power BI was my first attempt, but my required output format is in groups of columns, e.g. costs for current year, next year, year after, then income for current year, next year, year after etc. I gave up when the Table visual tried to add my desired columns as rows, but maybe I could extract the table in that “tidy” format from Power BI and then create a Pivot table in Excel in the desired format that I can then copy the flat table data rows into another financial model that needs that format. Or even direct from the Matrix Power BI visual if that supports it.
I’ll do some more digging. Thanks again

**Comment by josesamos** [comment]
You're welcome. 

Power Query can be used from Power BI and from Excel. I don't know if you have considered it.

**Comment by josesamos** [comment]
I have included that functionality in a new package. https://github.com/josesamos/geomultistar
When a multistar structure has been generated it can be exported as a flat table.

**Comment by josesamos** [comment]
Hope that helps. Comments or suggestions are welcome.

**Comment by josesamos** [comment]
The new package with that functionality is available from CRAN: https://CRAN.R-project.org/package=geomultistar

**Comment by sheepworrier** [comment]
Great work 👍 In the end I read up on quosures to define a function that would read in each of the FACT tables, widen it using the DIMENSION tables, then append each one into a large data frame.  I could then `unite` the columns I wanted to `pivot_wider`.  If I have to do something like this again I might look at writing something that will read in my SQL schema into a `multistar` object.  Have you seen the visualisations produced by https://github.com/bergant/datamodelr? That would fit nicely with your package
